// Comprehensive Realistic Agricultural Dataset for Agro Mark (SIH Project)
// Covering major Indian crops, APMC mandis, transport fleets, verified buyers, and translations.

export const CROPS = [
  {
    id: 'onion',
    name: 'Onion',
    hindiName: 'कांदा / प्याज',
    category: 'Vegetable',
    icon: '🧅',
    defaultUnit: 'quintal',
    basePrice: 2450,
    msp: 1800,
    varieties: ['Nashik Red', 'Garwa (Rabi)', 'Pol (Kharif)', 'White Onion', 'Agrifound Dark Red'],
    shelfLifeDays: 45,
    perishable: true,
    description: 'High trading volume across Western & Northern India.'
  },
  {
    id: 'wheat',
    name: 'Wheat',
    hindiName: 'गेहूं',
    category: 'Grain',
    icon: '🌾',
    defaultUnit: 'quintal',
    basePrice: 2320,
    msp: 2275,
    varieties: ['Sharbati', 'Lokwan', 'HD-2967', 'PBW-343', 'Kalyan Sona'],
    shelfLifeDays: 180,
    perishable: false,
    description: 'Rabi staple crop with high government procurement & open market demand.'
  },
  {
    id: 'rice',
    name: 'Paddy / Rice',
    hindiName: 'धान / चावल',
    category: 'Grain',
    icon: '🍚',
    defaultUnit: 'quintal',
    basePrice: 2250,
    msp: 2183,
    varieties: ['Basmati 1121', 'Pusa Basmati', 'Sona Masoori', 'IR-64', 'Kolam'],
    shelfLifeDays: 365,
    perishable: false,
    description: 'Major Kharif crop with strong domestic and export market value.'
  },
  {
    id: 'tomato',
    name: 'Tomato',
    hindiName: 'टमाटर',
    category: 'Vegetable',
    icon: '🍅',
    defaultUnit: 'quintal',
    basePrice: 1950,
    msp: 1200,
    varieties: ['Hybrid Vaishali', 'Abhinav', 'Pusa Ruby', 'Arka Rakshak', 'Desi Local'],
    shelfLifeDays: 7,
    perishable: true,
    description: 'Highly perishable vegetable prone to rapid seasonal price swings.'
  },
  {
    id: 'potato',
    name: 'Potato',
    hindiName: 'आलू',
    category: 'Vegetable',
    icon: '🥔',
    defaultUnit: 'quintal',
    basePrice: 1650,
    msp: 1100,
    varieties: ['Kufri Jyoti', 'Kufri Bahar', 'Kufri Chipsona', 'Pukhraj', 'Lal Gulaab'],
    shelfLifeDays: 90,
    perishable: false,
    description: 'Staple vegetable with cold-storage dynamics and steady market demand.'
  },
  {
    id: 'cotton',
    name: 'Cotton',
    hindiName: 'कपास',
    category: 'Cash Crop',
    icon: '☁️',
    defaultUnit: 'quintal',
    basePrice: 7150,
    msp: 7020,
    varieties: ['BT Cotton Hybrid', 'Shankar-6', 'DCH-32', 'MCU-5', 'Suvin'],
    shelfLifeDays: 180,
    perishable: false,
    description: 'High value commercial crop traded across ginning and spinning mills.'
  },
  {
    id: 'soybean',
    name: 'Soybean',
    hindiName: 'सोयाबीन',
    category: 'Oilseed',
    icon: '🌱',
    defaultUnit: 'quintal',
    basePrice: 4920,
    msp: 4892,
    varieties: ['JS-335', 'JS-9560', 'NRC-37', 'MACS-1407', 'RVS-2001-4'],
    shelfLifeDays: 120,
    perishable: false,
    description: 'Oilseed with intense industrial crushing & export meal demand.'
  },
  {
    id: 'maize',
    name: 'Maize / Corn',
    hindiName: 'मक्का',
    category: 'Grain',
    icon: '🌽',
    defaultUnit: 'quintal',
    basePrice: 2120,
    msp: 2090,
    varieties: ['DeKalb 9108', 'Pioneer 3396', 'African Tall', 'Ganga-5', 'Sweet Corn'],
    shelfLifeDays: 120,
    perishable: false,
    description: 'Widely used in poultry feed, starch industry and ethanol production.'
  },
  {
    id: 'mustard',
    name: 'Mustard',
    hindiName: 'सरसों',
    category: 'Oilseed',
    icon: '🌼',
    defaultUnit: 'quintal',
    basePrice: 5650,
    msp: 5650,
    varieties: ['Pusa Bold', 'Giriraj', 'Varuna', 'RH-30', 'Kranti'],
    shelfLifeDays: 180,
    perishable: false,
    description: 'Major rabi oilseed crop in northern & western belts.'
  },
  {
    id: 'garlic',
    name: 'Garlic',
    hindiName: 'लहसुन',
    category: 'Spices',
    icon: '🧄',
    defaultUnit: 'quintal',
    basePrice: 11500,
    msp: 8000,
    varieties: ['Yamuna Safed (G-1)', 'Godavari', 'Amleta', 'Ooty-1', 'G-282'],
    shelfLifeDays: 90,
    perishable: false,
    description: 'High cash value spice with strong wholesale demand.'
  }
];

export const QUALITY_GRADES = [
  {
    id: 'grade_a_plus',
    name: 'Grade A+ (Export / Premium)',
    multiplier: 1.10,
    priceBonusPercent: 10,
    description: 'Uniform size, optimal moisture (<10%), zero blemishes, clean sort.',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300'
  },
  {
    id: 'grade_a',
    name: 'Grade A (Superior Quality)',
    multiplier: 1.05,
    priceBonusPercent: 5,
    description: 'Good size grading, moisture <12%, minimal sorting defects.',
    badgeColor: 'bg-green-100 text-green-800 border-green-300'
  },
  {
    id: 'grade_b',
    name: 'Grade B (Standard / FAQ)',
    multiplier: 1.00,
    priceBonusPercent: 0,
    description: 'Fair Average Quality (FAQ), standard mandi specifications.',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300'
  },
  {
    id: 'grade_c',
    name: 'Grade C (Commercial / Mixed)',
    multiplier: 0.90,
    priceBonusPercent: -10,
    description: 'Mixed sizes, higher moisture (>15%), requires grading at mandi.',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300'
  }
];

export const MANDIS = [
  {
    id: 'mandi-lasalgaon',
    name: 'Lasalgaon APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    lat: 20.1472,
    lng: 74.2268,
    transportRatePerKm: 12.5,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 20.0,
    avgDailyArrivals: 3500,
    rating: 4.9,
    tradingHours: '08:00 AM - 05:00 PM',
    famousFor: ['Onion', 'Tomato', 'Grapes', 'Wheat']
  },
  {
    id: 'mandi-pimpalgaon',
    name: 'Pimpalgaon Baswant APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    lat: 20.1718,
    lng: 73.9856,
    transportRatePerKm: 12.0,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 20.0,
    avgDailyArrivals: 2800,
    rating: 4.8,
    tradingHours: '08:30 AM - 04:30 PM',
    famousFor: ['Tomato', 'Onion', 'Soybean']
  },
  {
    id: 'mandi-nashik',
    name: 'Nashik City APMC',
    district: 'Nashik',
    state: 'Maharashtra',
    lat: 19.9975,
    lng: 73.7898,
    transportRatePerKm: 12.0,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 22.0,
    avgDailyArrivals: 2100,
    rating: 4.7,
    tradingHours: '09:00 AM - 06:00 PM',
    famousFor: ['Vegetables', 'Paddy', 'Wheat']
  },
  {
    id: 'mandi-pune',
    name: 'Pune APMC (Gultekdi)',
    district: 'Pune',
    state: 'Maharashtra',
    lat: 18.4988,
    lng: 73.8647,
    transportRatePerKm: 14.0,
    marketFeePercent: 1.25,
    handlingFeePerQtl: 25.0,
    avgDailyArrivals: 6200,
    rating: 4.6,
    tradingHours: '06:00 AM - 04:00 PM',
    famousFor: ['Onion', 'Potato', 'Vegetables', 'Fruits']
  },
  {
    id: 'mandi-vashi',
    name: 'Mumbai APMC (Vashi)',
    district: 'Thane / Navi Mumbai',
    state: 'Maharashtra',
    lat: 19.0760,
    lng: 72.9984,
    transportRatePerKm: 16.5,
    marketFeePercent: 1.5,
    handlingFeePerQtl: 32.0,
    avgDailyArrivals: 9800,
    rating: 4.6,
    tradingHours: '05:00 AM - 03:00 PM',
    famousFor: ['Onion', 'Potato', 'Fruits', 'Grain Terminal']
  },
  {
    id: 'mandi-azadpur',
    name: 'Azadpur Mandi',
    district: 'North Delhi',
    state: 'Delhi',
    lat: 28.7088,
    lng: 77.1751,
    transportRatePerKm: 16.0,
    marketFeePercent: 1.5,
    handlingFeePerQtl: 30.0,
    avgDailyArrivals: 14500,
    rating: 4.5,
    tradingHours: '04:00 AM - 02:00 PM',
    famousFor: ['National Terminal', 'Vegetables', 'Fruits', 'Onion']
  },
  {
    id: 'mandi-indore',
    name: 'Indore APMC (Khandwa Rd)',
    district: 'Indore',
    state: 'Madhya Pradesh',
    lat: 22.7196,
    lng: 75.8577,
    transportRatePerKm: 13.0,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 22.0,
    avgDailyArrivals: 5100,
    rating: 4.8,
    tradingHours: '08:00 AM - 05:00 PM',
    famousFor: ['Soybean', 'Wheat', 'Garlic', 'Gram']
  },
  {
    id: 'mandi-kurnool',
    name: 'Kurnool APMC',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    lat: 15.8281,
    lng: 78.0373,
    transportRatePerKm: 12.5,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 20.0,
    avgDailyArrivals: 3200,
    rating: 4.7,
    tradingHours: '08:00 AM - 04:00 PM',
    famousFor: ['Onion', 'Cotton', 'Chili', 'Paddy']
  },
  {
    id: 'mandi-khanna',
    name: 'Khanna Grain Market',
    district: 'Ludhiana',
    state: 'Punjab',
    lat: 30.7046,
    lng: 76.2163,
    transportRatePerKm: 14.5,
    marketFeePercent: 1.0,
    handlingFeePerQtl: 24.0,
    avgDailyArrivals: 12000,
    rating: 4.9,
    tradingHours: '07:00 AM - 06:00 PM',
    famousFor: ['Wheat', 'Paddy', 'Asia Largest Grain Mandi']
  },
  {
    id: 'mandi-surat',
    name: 'Surat APMC',
    district: 'Surat',
    state: 'Gujarat',
    lat: 21.1702,
    lng: 72.8311,
    transportRatePerKm: 13.5,
    marketFeePercent: 1.1,
    handlingFeePerQtl: 24.0,
    avgDailyArrivals: 4300,
    rating: 4.7,
    tradingHours: '07:30 AM - 04:30 PM',
    famousFor: ['Vegetables', 'Cotton', 'Paddy']
  }
];

export const VEHICLES = [
  {
    id: 'mini_truck',
    name: 'Mini Truck (Tata Ace / Chota Hathi)',
    capacityQuintals: 15,
    capacityKg: 1500,
    baseRatePerKm: 12,
    fixedLoadingCharge: 300,
    icon: '🛻',
    suitableFor: 'Small harvest batches (up to 15 Qtl)'
  },
  {
    id: 'pickup',
    name: 'Pickup Truck (Mahindra Bolero Maxi)',
    capacityQuintals: 30,
    capacityKg: 3000,
    baseRatePerKm: 15,
    fixedLoadingCharge: 500,
    icon: '🚙',
    suitableFor: 'Medium harvest (15 - 30 Qtl)'
  },
  {
    id: 'tractor_trolley',
    name: 'Tractor Trolley (Farmer Own/Rent)',
    capacityQuintals: 50,
    capacityKg: 5000,
    baseRatePerKm: 11,
    fixedLoadingCharge: 400,
    icon: '🚜',
    suitableFor: 'Local mandi transport (under 50 km)'
  },
  {
    id: 'medium_truck',
    name: '14ft Medium Truck (Eicher Pro)',
    capacityQuintals: 80,
    capacityKg: 8000,
    baseRatePerKm: 20,
    fixedLoadingCharge: 900,
    icon: '🚚',
    suitableFor: 'Large harvest or interstate trade (up to 80 Qtl)'
  },
  {
    id: 'heavy_truck',
    name: '10-Wheeler Heavy Truck (Tata 2518)',
    capacityQuintals: 200,
    capacityKg: 20000,
    baseRatePerKm: 32,
    fixedLoadingCharge: 1500,
    icon: '🚛',
    suitableFor: 'Bulk trader & aggregation shipments (up to 200 Qtl)'
  }
];

export const VERIFIED_BUYERS = [
  {
    id: 'buyer-101',
    name: 'Kisan Agro Traders & Commission Agents',
    mandiId: 'mandi-lasalgaon',
    mandiName: 'Lasalgaon APMC',
    licenseNo: 'MH-NSK-APMC-7842',
    rating: 4.9,
    dealsCount: 1420,
    paymentSpeed: 'Instant UPI on Delivery',
    verified: true,
    phone: '+91 98231 45678',
    type: 'Licensed APMC Commission Agent'
  },
  {
    id: 'buyer-102',
    name: 'Maha Agri Exports Pvt Ltd',
    mandiId: 'mandi-lasalgaon',
    mandiName: 'Lasalgaon APMC',
    licenseNo: 'MH-NSK-APMC-9011',
    rating: 4.8,
    dealsCount: 890,
    paymentSpeed: 'Direct Bank NEFT (2 Hrs)',
    verified: true,
    phone: '+91 94222 67890',
    type: 'Institutional Export Buyer'
  },
  {
    id: 'buyer-103',
    name: 'Gultekdi Food Corp Traders',
    mandiId: 'mandi-pune',
    mandiName: 'Pune APMC',
    licenseNo: 'MH-PUN-APMC-3120',
    rating: 4.7,
    dealsCount: 2300,
    paymentSpeed: 'Instant UPI on Weighment',
    verified: true,
    phone: '+91 98810 12345',
    type: 'Wholesale Food Distributor'
  },
  {
    id: 'buyer-104',
    name: 'Vashi Modern Wholesale Hub',
    mandiId: 'mandi-vashi',
    mandiName: 'Mumbai APMC',
    licenseNo: 'MH-THN-APMC-5541',
    rating: 4.8,
    dealsCount: 3100,
    paymentSpeed: 'Guaranteed Escrow Release',
    verified: true,
    phone: '+91 98190 99887',
    type: 'Metro Terminal Aggregator'
  },
  {
    id: 'buyer-105',
    name: 'Pimpalgaon Farmer Producer Co (FPO)',
    mandiId: 'mandi-pimpalgaon',
    mandiName: 'Pimpalgaon Baswant APMC',
    licenseNo: 'MH-NSK-FPO-1044',
    rating: 4.9,
    dealsCount: 960,
    paymentSpeed: 'Instant Direct Farmer Credit',
    verified: true,
    phone: '+91 94050 44556',
    type: 'Farmer Producer Organization'
  }
];

export const TRANSPORTERS = [
  {
    id: 'trans-01',
    name: 'Gramin Agri Logistics Co.',
    driverName: 'Rameshwar Patil',
    driverPhone: '+91 97654 32100',
    vehicleNo: 'MH 15 EG 4492',
    vehicleType: 'Tata Ace (1.5 Ton)',
    rating: 4.9,
    tripsCompleted: 430,
    gpsDeviceId: 'GPS-TRK-9801'
  },
  {
    id: 'trans-02',
    name: 'Jai Kisan Freight Services',
    driverName: 'Sanjay Deshmukh',
    driverPhone: '+91 98220 87654',
    vehicleNo: 'MH 15 BX 8812',
    vehicleType: 'Mahindra Bolero Maxi (3 Ton)',
    rating: 4.8,
    tripsCompleted: 610,
    gpsDeviceId: 'GPS-TRK-7712'
  },
  {
    id: 'trans-03',
    name: 'Shivkripa Farm Transporters',
    driverName: 'Mahesh Jadhav',
    driverPhone: '+91 94230 11223',
    vehicleNo: 'MH 12 QX 3390',
    vehicleType: '14ft Eicher Pro (8 Ton)',
    rating: 4.9,
    tripsCompleted: 850,
    gpsDeviceId: 'GPS-TRK-5544'
  }
];

// Pre-seeded Demo Orders for instant tracking inspection
export const DEMO_ORDERS = [
  {
    id: 'AGRO-ORD-2026-881',
    farmerName: 'Adarsh Dubey',
    farmerPhone: '+91 98765 43210',
    originLocation: 'Chandwad Village, Nashik, Maharashtra',
    cropId: 'onion',
    cropName: 'Onion (कांदा)',
    variety: 'Garwa (Rabi)',
    quantityQtl: 50,
    grade: 'Grade A (Superior)',
    mandiId: 'mandi-lasalgaon',
    mandiName: 'Lasalgaon APMC',
    agreedPricePerQtl: 2450,
    grossAmount: 122500,
    transportCost: 812.50,
    mandiFee: 1225.00,
    handlingFee: 1000.00,
    netFarmerPayout: 119462.50,
    status: 'IN_TRANSIT', // ORDER_PLACED | PICKED_UP | IN_TRANSIT | AT_MANDI | DELIVERED
    orderDate: '2026-08-24T14:30:00Z',
    scheduledPickup: '2026-08-24T16:00:00Z',
    estimatedDelivery: '2026-08-24T18:45:00Z',
    buyer: VERIFIED_BUYERS[0],
    transporter: TRANSPORTERS[0],
    otpCode: '4829',
    escrowStatus: 'ESCROW_LOCKED_70%',
    milestones: [
      { step: 1, title: 'Order Placed & Deal Locked', timestamp: '14:30 PM', completed: true, details: 'Price locked at ₹2,450/qtl. 20% advance escrow guaranteed.' },
      { step: 2, title: 'Transporter Assigned & Picked Up', timestamp: '16:15 PM', completed: true, details: 'Rameshwar Patil loaded 50 Quintals at Chandwad farm gate.' },
      { step: 3, title: 'In Transit (Live GPS Tracking)', timestamp: '17:05 PM', completed: true, details: 'Vehicle MH 15 EG 4492 is moving via NH-752G. Speed: 42 km/h.' },
      { step: 4, title: 'Out for Delivery / Reached Mandi Gate', timestamp: 'Estimated 18:30 PM', completed: false, details: 'Entering Lasalgaon APMC Gate 2 for electronic weighment.' },
      { step: 5, title: 'Delivered, Quality Checked & Final Payout', timestamp: 'Pending OTP', completed: false, details: 'Share OTP 4829 upon physical handover to release full ₹1,19,462.50' }
    ],
    liveGps: {
      latitude: 20.1250,
      longitude: 74.1950,
      speedKmH: 44,
      distanceRemainingKm: 18.4,
      etaMinutes: 28
    }
  }
];

export const TRANSLATIONS = {
  en: {
    appName: 'Agro Mark',
    tagline: 'AI-Based Personalized Agricultural Market Intelligence & Best-Market Recommendation System',
    step1Title: '1. Crop Selection',
    step2Title: '2. Location & Logistics',
    step3Title: '3. Mandi Comparison (Raw Data)',
    step4Title: '4. AI Analysis Engine',
    step5Title: '5. Best Market Recommendation',
    step6Title: '6. Online Selling System',
    step7Title: '7. Delivery Tracking System',
    step8Title: '8. Farmer Report & Analytics',
    findBestMarket: 'Find Best Market',
    selectCrop: 'Select Crop',
    selectVariety: 'Select Variety',
    quantity: 'Quantity',
    qualityGrade: 'Quality / Grade',
    sellingDate: 'Expected Selling Date',
    currentLocation: 'Your Location',
    calculateReturns: 'Calculate Best Market & Net Return',
    recommended: 'RECOMMENDED',
    netReturn: 'Estimated Net Return',
    grossRevenue: 'Gross Revenue',
    transportCost: 'Transportation Cost',
    mandiFees: 'Mandi Fees & Cess',
    handlingCharges: 'Handling / Hamali Charges',
    sellNow: 'Sell to Recommended Buyer',
    trackDelivery: 'Track Live Delivery',
    downloadReport: 'Download PDF Report'
  },
  hi: {
    appName: 'एग्रो मार्क',
    tagline: 'एआई-आधारित व्यक्तिगत कृषि मंडी बुद्धिमत्ता एवं सर्वोत्तम मंडी सिफारिश प्रणाली',
    step1Title: '1. फसल चयन',
    step2Title: '2. स्थान एवं परिवहन',
    step3Title: '3. मंडी तुलना (मूल आंकड़े)',
    step4Title: '4. एआई विश्लेषण इंजन',
    step5Title: '5. सर्वोत्तम मंडी सिफारिश',
    step6Title: '6. ऑनलाइन बिक्री प्रणाली',
    step7Title: '7. डिलीवरी ट्रैकिंग प्रणाली',
    step8Title: '8. किसान रिपोर्ट एवं विश्लेषण',
    findBestMarket: 'सर्वोत्तम मंडी खोजें',
    selectCrop: 'फसल चुनें',
    selectVariety: 'किस्म चुनें',
    quantity: 'मात्रा',
    qualityGrade: 'गुणवत्ता / ग्रेड',
    sellingDate: 'अपेक्षित बिक्री तिथि',
    currentLocation: 'आपका स्थान',
    calculateReturns: 'सर्वोत्तम मंडी एवं शुद्ध आय की गणना करें',
    recommended: 'सर्वश्रेष्ठ विकल्प',
    netReturn: 'अनुमानित शुद्ध आय (Net Return)',
    grossRevenue: 'कुल बिक्री मूल्य (Gross)',
    transportCost: 'परिवहन किराया',
    mandiFees: 'मंडी टैक्स व सेस',
    handlingCharges: 'हमाली व तुलाई खर्च',
    sellNow: 'अनुशंसित खरीदार को बेचें',
    trackDelivery: 'लाइव डिलीवरी ट्रैक करें',
    downloadReport: 'पीडीएफ रिपोर्ट डाउनलोड करें'
  },
  mr: {
    appName: 'ॲग्रो मार्क',
    tagline: 'कृत्रिम बुद्धिमत्ता आधारित शेतमाल बाजार बुद्धिमत्ता व सर्वोत्तम बाजार शिफारस प्रणाली',
    step1Title: '१. पीक निवड',
    step2Title: '२. स्थान आणि वाहतूक',
    step3Title: '३. बाजार समिती तुलना',
    step4Title: '४. एआई विश्लेषण प्रणाली',
    step5Title: '५. सर्वोत्तम बाजार शिफारस',
    step6Title: '६. ऑनलाइन विक्री प्रणाली',
    step7Title: '७. वाहतूक ट्रॅकिंग प्रणाली',
    step8Title: '८. शेतकरी अहवाल',
    findBestMarket: 'सर्वोत्तम बाजार शोधा',
    selectCrop: 'पीक निवडा',
    selectVariety: 'वाण निवडा',
    quantity: 'प्रमाण',
    qualityGrade: 'गुणवत्ता / ग्रेड',
    sellingDate: 'अपेक्षित विक्री तारीख',
    currentLocation: 'आपले ठिकाण',
    calculateReturns: 'सर्वोत्तम बाजार व निव्वळ नफा शोधा',
    recommended: 'सर्वोत्तम निवड',
    netReturn: 'अंदाजे निव्वळ नफा (Net Return)',
    grossRevenue: 'एकूण रक्कम',
    transportCost: 'वाहतूक खर्च',
    mandiFees: 'बाजार समिती कर',
    handlingCharges: 'हमाली व तोलाई',
    sellNow: 'नोंदणीकृत खरेदीदारास विका',
    trackDelivery: 'थेट ट्रॅकिंग पहा',
    downloadReport: 'अहवाल डाउनलोड करा'
  }
};
